// Document color library: named colors with a light value and an optional dark value.
// Pixels reference a library color as `c:<id>`, so changing the color updates every pixel using it.
import type { ColorToken, Doc, Fill } from './types';

export const colorRef = (id: string): Fill => `c:${id}`;
export const isColorRef = (f: Fill) => f.startsWith('c:');
export const colorIdOf = (f: Fill) => (isColorRef(f) ? f.slice(2) : null);

/** CSS-safe slug of a color name: "Yellow faint" -> "yellow-faint". */
export const slugOf = (name: string) =>
  name.toLowerCase().normalize('NFKD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

/** Exported CSS variable name for a color. */
export const cssVarOf = (c: ColorToken) => `--pixl-${slugOf(c.name) || c.id}`;
/** Variable used inside the editor (by id, so renames never break rendering). */
export const editorVarOf = (id: string) => `--pixlc-${id}`;

export const findColor = (doc: Doc, id: string | null) => (id ? doc.colors?.find((c) => c.id === id) : undefined);

/** Problems with a color's name: empty, or a slug that collides with another color. */
export function nameProblem(doc: Doc, c: ColorToken): string | null {
  const slug = slugOf(c.name);
  if (!slug) return 'Name needs letters or digits';
  const clash = (doc.colors ?? []).find((o) => o.id !== c.id && slugOf(o.name) === slug);
  return clash ? `Same variable as "${clash.name}"` : null;
}

/** Stylesheet for the editor: light values by default, dark values under the dark theme class. */
export function editorColorCss(colors: ColorToken[] = []): string {
  if (!colors.length) return '';
  const light = colors.map((c) => `${editorVarOf(c.id)}: ${c.light};`).join(' ');
  const dark = colors.map((c) => `${editorVarOf(c.id)}: ${c.dark ?? c.light};`).join(' ');
  return `html { ${light} }\nhtml.theme-dark { ${dark} }\n`;
}

/** colors.css shipped with the package. Dark values follow prefers-color-scheme, like systm. */
export function exportColorCss(colors: ColorToken[] = []): string {
  const head = '/* Generated by Pixl Editor from pixl.json. Do not edit by hand. */\n';
  if (!colors.length) return head;
  const light = colors.map((c) => `  ${cssVarOf(c)}: ${c.light};`).join('\n');
  const darkOnes = colors.filter((c) => c.dark && c.dark !== c.light);
  const dark = darkOnes.length ? `\n@media (prefers-color-scheme: dark) {\n  :root {\n${darkOnes.map((c) => `    ${cssVarOf(c)}: ${c.dark};`).join('\n')}\n  }\n}\n` : '';
  return `${head}:root {\n${light}\n}\n${dark}`;
}

/** Count pixels (rects) using a fill across the document. */
export function usageOf(doc: Doc, fill: Fill): number {
  let n = 0;
  for (const a of doc.artboards) {
    for (const r of a.rects) if (r.fill === fill) n++;
    for (const ic of a.icons) for (const r of ic.rects) if (r.fill === fill) n++;
  }
  return n;
}
